name: ✨Feature Request
description: Request a new feature or enhancement
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why is this feature important?
    validations:
      required: false
  - type: textarea
    id: how
    attributes:
      label: How
      description: How do you propose this feature be implemented?
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like identical solutions, links, screenshots, etc.